name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u vinayakojha47 --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag githubactions:latest
    - name: Push Docker image
      run: docker push vinayakojha47/githubactions:latest
