name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: |
        IMAGE_TAG=$(date +%s)
        docker build . --file Dockerfile --tag vinayakojha47/my-image-name:$IMAGE_TAG
        echo IMAGE_TAG=$IMAGE_TAG >> $GITHUB_ENV

    - name: Verify Docker Hub Credentials
      run: |
        echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}"
        echo "DOCKER_PASSWORD is set"

    - name: Log in to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u vinayakojha47 -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: docker push vinayakojha47/my-image-name:${{ env.IMAGE_TAG }}
