name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u vinayakojha47 --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag vinayakojha47/githubactions:latest
    - name: Push Docker image
      run: docker push vinayakojha47/githubactions:latest

    - name: Set up kubectl
      run: |
        sudo apt-get update
        sudo apt-get install -y kubectl
        
    - name: Set up Kubeconfig
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f nodejsapp.yaml
        kubectl rollout restart deployment nodejs-app
